clone_folder: "c:\\WORK"
clone_depth: 5

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x86_64

install:
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y autohotkey
  - appveyor DownloadFile "https://github.com/NickSeagull/pahket/releases/download/v0.0.0/pahket.exe"
  - refreshenv

before_build:
  - .\pahket.exe install

build_script:
  - & .\run_tests.ps1

skip_commits:
  files:
    - "**/*.md"
    - "**/*.html"
    - ".gitignore"
